ui:
  port: ""
  image: icr.io/ai-services/chatbot-ui:v0.0.56

backend:
  port: ""
  image: icr.io/ai-services/chatbot-service:v0.0.36
  log_level: "INFO"
  chatbot:
    searchMode: "hybrid"
    numChunksPostReranker: 3
    rerank: true
    systemPrompt: ""
mcp:
  image: icr.io/ai-services/ai-services-mcp:v0.0.4
  port: "5001"
