apiVersion: v1
name: reranker-vllm-spyre
description: A Helm chart for deploying the Reranker model using vLLM Spyre inference on OpenShift (via KServe InferenceService)
type: application

version: 0.0.1
appVersion: "0.0.1"
