FROM registry.access.redhat.com/ubi9/ubi-minimal:9.8

RUN microdnf install -y python3.12-devel && \
    curl -o /tmp/epel-release.rpm https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm && \
    rpm -ivh /tmp/epel-release.rpm && \
    rm -f /tmp/epel-release.rpm && \
    microdnf clean all && \
    curl -sSL https://bootstrap.pypa.io/get-pip.py | python3.12 - && \
    rm -rf /usr/bin/python && rm -rf /usr/bin/python3 && \
    ln -s /usr/bin/python3.12 /usr/bin/python && ln -s /usr/bin/python3.12 /usr/bin/python3

COPY requirements.txt .

RUN python -m venv /var/venv && source /var/venv/bin/activate && \
    pip install --upgrade pip setuptools wheel && \
    pip install -r requirements.txt \
        --extra-index-url https://wheels.developerfirst.ibm.com/ppc64le/linux \
        --prefer-binary && \
    pip cache purge
