apiVersion: v2
name: reranker-vllm-cpu
description: A Helm chart for deploying the Reranker model using vLLM CPU inference on OpenShift (via KServe InferenceService)
type: application

version: 0.0.1
appVersion: "0.0.1"
