ui:
  port: ""
  image: icr.io/ai-services-cicd/catalog-ui:v0.0.3

backend:
  port: ""
  image: icr.io/ai-services-cicd/ai-services:0.0.3
  runtime: ""
  adminPasswordHash: ""
  baseDir: "/var/lib/ai-services"
  podman:
    uri: "/run/podman/podman.sock"

db:
  port: ""
  image: icr.io/ai-services-private/postgres:18
  user: "admin"
  database: "ai_services"
  password: ""
  dataPath: ""  # Will be set dynamically based on backend.baseDir
  resources:
    requests:
      memory: "512Mi"
    limits:
      memory: "1Gi"
