apiVersion: v2
name: embedding-vllm-cpu
description: A Helm chart for deploying the Embedding model using vLLM CPU inference on OpenShift (via KServe InferenceService)
type: application

version: 0.0.1
appVersion: "0.0.1"
