apiVersion: v2
name: embedding-vllm-cpu
description: A Helm chart for deploying the Embedding model using vLLM CPU inference on OpenShift (via KServe InferenceService)
type: application

version: 1.0.0
appVersion: "1.0.0"
