FROM services-common:latest

WORKDIR /opt/services

ENV PYTHONPATH=/opt/services

COPY requirements.txt digitize/
RUN source /var/venv/bin/activate && pip install -r digitize/requirements.txt && pip cache purge

COPY . digitize/

CMD ["/var/venv/bin/python", "-m", "uvicorn", "digitize.app:app", \
     "--host", "0.0.0.0", "--port", "4000", \
     "--loop", "uvloop", "--http", "httptools"]
