apiVersion: v1
kind: Service
metadata:
  name: "extract-api"
  labels:
    ai-services.io/service: {{ .Release.Name }}
    ai-services.io/template: {{ .Values.templateID }}
    ai-services.io/version: {{ default .Chart.AppVersion | quote }}
spec:
  selector:
    ai-services.io/service: {{ .Release.Name }}
    ai-services.io/component: extract-api
  ports:
    - name: extract-api
      port: 9500
      targetPort: 9500
      protocol: TCP
