apiVersion: batch/v1
kind: CronJob
metadata:
  name: "{{ .Release.Name }}--clean-docs"
  labels:
    ai-services.io/application: {{ .Release.Name }}
    ai-services.io/template: {{ .Chart.Name }}
    ai-services.io/version: {{ .Values.app.version | default .Chart.AppVersion | quote }}
spec:
  schedule: "0 0 1 1 *" # never runs as suspend is set to true
  suspend: true
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          containers:
            - name: clean-docs
              image: "{{ .Values.backend.image }}"
              imagePullPolicy: "{{ .Values.imagePullPolicy }}"
              command:
                - "/var/venv/bin/python"
                - "-m"
                - "ingest.cli"
                - "clean-db"
              resources:
                requests:
                  memory: "1Gi"
                limits:
                  memory: "1Gi"
              env:
              - name: OPENSEARCH_HOST
                value: "{{ .Release.Name }}--opensearch"
              - name: OPENSEARCH_PORT
                value: "9200"
              - name: OPENSEARCH_DB_PREFIX
                value: "RAG_DB"
              - name: OPENSEARCH_INDEX_NAME
                value: "RAG_INDEX"
              - name: OPENSEARCH_USERNAME
                valueFrom:
                  secretKeyRef:
                    name: "{{ .Release.Name }}--opensearch-auth"
                    key: username
              - name: OPENSEARCH_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: "{{ .Release.Name }}--opensearch-auth"
                    key: password
              volumeMounts:
                - name: cache
                  mountPath: /var/cache
          restartPolicy: Never
          volumes:
            - name: cache
              persistentVolumeClaim:
                claimName: "{{ .Release.Name }}--cache"
