apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: granite-3-3-8b-instruct
  annotations:
    security.opendatahub.io/enable-auth: "false"
    serving.kserve.io/deploymentMode: RawDeployment
  labels:
    networking.kserve.io/visibility: cluster-local
    ai-services.io/application: {{ .Release.Name }}
    ai-services.io/template: {{ .Chart.Name }}
    ai-services.io/version: {{ default .Chart.AppVersion | quote }}
spec:
  predictor:
    automountServiceAccountToken: false
    deploymentStrategy:
      type: Recreate
    maxReplicas: 1
    minReplicas: 1
    model:
      args:
      - '--tensor-parallel-size=4 '
      - '--max-model-len=32768 '
      - --max-num-seqs=32
      env:
      - name: VLLM_SPYRE_USE_CB
        value: "1"
      modelFormat:
        name: vLLM
      name: ""
      resources:
        limits:
          cpu: "140"
          memory: 900Gi
          ibm.com/spyre_pf: "4"
        requests:
          cpu: "140"
          memory: 900Gi
          ibm.com/spyre_pf: "4"
      runtime: instruct
      storageUri: {{ .Values.instruct.storageUri }}
---
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: granite-embedding-278m-multilingual
  annotations:
    security.opendatahub.io/enable-auth: "false"
    serving.kserve.io/deploymentMode: RawDeployment
  labels:
    networking.kserve.io/visibility: cluster-local
    ai-services.io/application: {{ .Release.Name }}
    ai-services.io/template: {{ .Chart.Name }}
    ai-services.io/version: {{ default .Chart.AppVersion | quote }}
spec:
  predictor:
    automountServiceAccountToken: false
    deploymentStrategy:
      type: Recreate
    maxReplicas: 1
    minReplicas: 1
    model:
      modelFormat:
        name: vLLM
      name: ""
      resources:
        limits:
          cpu: "4"
          memory: 8Gi
        requests:
          cpu: "4"
          memory: 8Gi
      runtime: embedding
      storageUri: {{ .Values.embedding.storageUri }}
---
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: bge-reranker-v2-m3
  annotations:
    security.opendatahub.io/enable-auth: "false"
    serving.kserve.io/deploymentMode: RawDeployment
  labels:
    networking.kserve.io/visibility: cluster-local
    ai-services.io/application: {{ .Release.Name }}
    ai-services.io/template: {{ .Chart.Name }}
    ai-services.io/version: {{ default .Chart.AppVersion | quote }}
spec:
  predictor:
    automountServiceAccountToken: false
    deploymentStrategy:
      type: Recreate
    maxReplicas: 1
    minReplicas: 1
    model:
      modelFormat:
        name: vLLM
      name: ""
      resources:
        limits:
          cpu: "10"
          memory: 8Gi
        requests:
          cpu: "10"
          memory: 8Gi
      runtime: reranker
      storageUri: {{ .Values.reranker.storageUri }}
