apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ .Release.Name }}--opensearch"
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-storage-provisioner
  resources:
    requests:
      storage: "10Gi"
