apiVersion: v1
kind: Service
metadata:
  name: "chat-bot-backend"
  labels:
    ai-services.io/service: {{ .Release.Name }}
    ai-services.io/template: {{ .Chart.Name }}
    ai-services.io/version: {{ default .Chart.AppVersion | quote }}
spec:
  selector:
    ai-services.io/service: {{ .Release.Name }}
    ai-services.io/component: chat-bot-backend
  ports:
    - name: backend
      port: 5000
      targetPort: 5000
      protocol: TCP
