FROM registry.access.redhat.com/ubi9/ubi:9.7 as tools_builder

ARG DNF_FLAGS="--disablerepo=* --enablerepo=ubi-9-baseos-rpms --enablerepo=ubi-9-appstream-rpms"

ENV VIRTUAL_ENV=/opt/venv
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

COPY requirements.txt .

RUN dnf update ${DNF_FLAGS} -y \
  && dnf install ${DNF_FLAGS} -y gcc \
  python3.12-pip python3.12 python3.12-devel python3-pexpect python3-ptyprocess python3-pyyaml python3-file-magic \
  && python3.12 -m venv ${VIRTUAL_ENV} \
  && pip install -r requirements.txt \
  && rm -rf /var/cache/dnf && dnf clean all -y

FROM registry.access.redhat.com/ubi9/ubi-minimal:9.7

ARG SR_VERSION
ARG DNF_FLAGS="--disablerepo=* --enablerepo=ubi-9-baseos-rpms --enablerepo=ubi-9-appstream-rpms"

ENV VIRTUAL_ENV=/opt/venv
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

COPY --from=tools_builder /opt/venv /opt/venv

RUN microdnf update ${DNF_FLAGS} -y && \
  microdnf install ${DNF_FLAGS} -y python3.12 && \
  ARCH=$(uname -m) && \
  if [ "$ARCH" = "ppc64le" ]; then \
  echo "Installing ServiceReport for ppc64le..." && \
  microdnf install ${DNF_FLAGS} -y systemd kmod sos python3-pyudev && \
  curl -LO https://public.dhe.ibm.com/software/server/POWER/Linux/yum/OSS/RHEL/9/ppc64le/ServiceReport-${SR_VERSION}.ppc64le.rpm && \
  rpm -ivh ServiceReport-${SR_VERSION}.ppc64le.rpm && \
  rm ServiceReport-${SR_VERSION}.ppc64le.rpm; \
  fi && \
  microdnf clean all
