apiVersion: v1
kind: Secret
metadata:
  name: "digitize-db-encryption-secret"
  labels:
    ai-services.io/service: {{ .Release.Name }}
    ai-services.io/template: {{ .Values.templateID }}
    ai-services.io/version: {{ default .Chart.AppVersion | quote }}
    ai-services.io/component: digitize
type: Opaque
stringData:
  db-encryption-key: {{ .Values.digitize.dbEncryptionKey | quote }}
