apiVersion: v1
kind: Secret
metadata:
  name: "catalog-connector-secret"
  labels:
    ai-services.io/application: {{ .Release.Name }}
    ai-services.io/template: {{ .Chart.Name }}
    ai-services.io/version: {{ default .Chart.AppVersion | quote }}
    ai-services.io/component: catalog
type: Opaque
stringData:
  connector-encryption-key: {{ .Values.backend.connectorEncryptionKey | quote }}
